name: ent
description: Entando ent cli tool
inputs:
  ent-command: # id of input
    description: 'ent command to run'
    required: true
    default: 'ent bundle pack --org=entando --stdout'
runs:
  using: 'docker'
  image: docker://registry.hub.docker.com/entando/ent:7.1.3_ocp-4.8_k8s_1.21
  args:
    - ${{ inputs.ent-command }}
